name: Tests

on:
  push:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew custom -x test -DcustomTags=UI -Dhost=http://213.139.208.111:4444/wd/hub || true

    - name: Allure report
      if: always()
      run: ./gradlew allureReport

    - name: Save results
      uses: actions/upload-artifact@v1
      with:
        name: allure-report
        path: build/reports/allure-report

